### PR TITLE
Multiple levels of Json Extraction

### PR DESCRIPTION
**Pull request by kotvisbj**
Use it by supplying multiple levels of Json Paths. They will be assigned to the schema by index. It will recurse up the tree to locate paths if they aren't found at the "rowpath" level.

This inherits from the current JsonExtractor.

[https://github.com/kotvisbj/UsqlCodeGenerationSample/blob/master/CodeGenerationSample.Scripts/JsonToCsv.usql](See an example usage here)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kotvisbj__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@kotvisbj__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by MikeRys** [comment]
Hi, thanks for the contribution. Could you please add some examples to the https://github.com/Azure/usql/tree/master/Examples/JSONExamples to show people how to use it?

**Comment by kotvisbj** [comment]
Sure, I just say this today, sorry about that.  Will add some right now.

**Comment by kotvisbj** [comment]
Ok Mike, the example has been added to this pull request.  Let me know if you have any issues.

**Pull request merged**
